apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-catalog
  template:
    metadata:
      labels:
        app: store-catalog
    spec:
      containers:
      - name: store-catalog
        image: itay80/smartshop:store-catalog-latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: store-catalog
spec:
  type: ClusterIP
  selector:
    app: store-catalog
  ports:
  - port: 3002
    targetPort: 3002
