apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-orders
  template:
    metadata:
      labels:
        app: store-orders
    spec:
      containers:
      - name: store-orders
        image: itay80/smartshop:store-orders-latest
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: store-orders
spec:
  type: ClusterIP
  selector:
    app: store-orders
  ports:
  - port: 3005
    targetPort: 3005
