apiVersion: v1
kind: Service
metadata:
  name: store-orders
  namespace: store
spec:
  selector:
    app: store-orders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: ClusterIP
