apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shmueliitay/retail-store-sample-app.git'
    targetRevision: main
    path: store-ui/deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
